INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Irene','1944-02-18','Lucas','euismod.ac.fermentum@utpharetrased.edu','+69 387-727-154','Santa Bárbara');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Brent','1969-07-10','Hart','tincidunt@turpis.co.uk','+75 117-496-417','Sète');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Jelani','1977-02-17','Gallegos','a.dui@Nullamut.com','+19 921-877-823','Tampa');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Eleanor','1959-12-11','Le','sodales.at.velit@lobortistellus.ca','+35 411-329-154','Colico');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Ainsley','1961-06-20','Gallegos','nisl.sem@id.com','+92 838-029-363','Moncrivello');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Carson','1941-05-15','Cantu','fermentum@quispedeSuspendisse.ca','+01 221-467-609','Mannekensvere');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Graham','1972-11-17','Jacobs','amet.faucibus@vehicula.ca','+45 742-878-466','Río Bueno');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Xanthus','1943-12-19','Wade','tellus.Suspendisse@sapien.edu','+64 653-133-599','Neusiedl am See');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Jena','1981-07-10','Patrick','gravida.molestie.arcu@pede.co.uk','+97 510-242-623','Harbour Grace');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Erin','1998-01-03','Richardson','ac.facilisis.facilisis@malesuadavelvenenatis.net','+45 786-742-777','Diego de Almagro');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Peter','1942-10-29','Luna','eu.metus.In@mauris.co.uk','+89 772-484-760','Devon');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Samson','1982-07-28','Bullock','arcu.Vestibulum.ante@interdumNuncsollicitudin.ca','+90 710-599-687','Sunderland');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Yasir','1976-03-17','Carlson','semper@NullafacilisiSed.net','+64 366-262-076','Heppignies');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Noel','1951-10-27','Mcpherson','Integer.vitae@disparturientmontes.com','+52 716-036-795','Grand Rapids');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Colorado','1941-08-27','Cash','ac.turpis@semvitaealiquam.com','+82 604-558-213','Pumanque');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Jasmine','1995-10-13','Forbes','mi@turpisegestasAliquam.net','+20 622-379-609','Mont-sur-Marchienne');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Ray','1944-10-06','Haley','ante@blandit.org','+47 312-388-395','Zuienkerke');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Lester','1941-12-29','Montoya','elit.pretium.et@quis.ca','+70 523-087-388','Sparwood');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Donovan','1982-06-20','Stewart','interdum.enim@gravida.org','+95 224-876-935','San Giovanni Lipioni');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Jin','1966-02-05','Mckinney','massa.Integer.vitae@Sedet.co.uk','+98 432-590-032','Graz');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Driscoll','1998-07-23','Horn','Nulla@sapien.ca','+12 742-803-439','Hualañé');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Mollie','1989-08-01','Vaughan','iaculis.aliquet.diam@vitaeerat.ca','+44 794-223-455','Drayton Valley');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Ronan','1944-08-20','Fitzgerald','vitae@inceptoshymenaeosMauris.com','+09 433-111-905','Killa Abdullah');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Ulysses','1967-07-20','Blake','risus.In.mi@facilisi.co.uk','+05 853-203-132','Cap-Rouge');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Magee','1972-08-09','Wheeler','dis.parturient.montes@quistristique.com','+25 679-540-407','Barranco Minas');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Dominique','1957-05-27','Klein','felis.Donec.tempor@estmauris.ca','+57 628-226-604','Clermont-Ferrand');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Erich','1942-02-19','Noble','lectus.sit.amet@quislectus.co.uk','+26 170-354-037','Dereham');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Griffin','1954-04-12','Warren','nec@vitaenibh.com','+30 735-436-945','Doel');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Ruby','1990-11-10','Noel','cubilia.Curae@tellus.org','+93 286-780-585','Guadalajara');
INSERT INTO Czytelnicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto]) VALUES('Zeus','1992-06-16','Macdonald','nec@eget.org','+18 922-078-145','Banda');

INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('et libero. Proin','Axel B. Sparks','Biały Kruk','1848-07-21',19);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('Nullam velit dui,','Armando T. Lott','Biały Kruk','1899-06-21',23);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('mi','Fuller H. Oneill','Biały Kruk','1858-01-25',21);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('Nam','Ivory G. Burton','Biały Kruk','1991-06-30',3);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('vel lectus. Cum sociis','Gil Q. Nielsen','Biały Kruk','1935-11-26',8);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('aptent taciti sociosqu','Eve B. Whitney','Biały Kruk','1913-11-10',8);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('sagittis. Duis gravida. Praesent','Hasad P. James','Biały Kruk','1963-02-24',8);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('magna,','Wallace R. Chang','Biały Kruk','1858-01-03',15);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('neque tellus,','Theodore K. Ingram','Biały Kruk','1831-11-16',15);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('lorem','Kirestin F. Bond','Gebethner i Wolff','1902-03-30',13);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('ante ipsum primis','Octavius K. Baker','Gebethner i Wolff','1920-08-30',4);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('sit amet,','Kiara I. Osborn','Gebethner i Wolff','1859-11-01',13);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('euismod','Yolanda R. Yates','Gebethner i Wolff','1969-08-01',17);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('tristique','Kathleen C. Landry','Gebethner i Wolff','1970-04-14',7);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('lorem. Donec elementum, lorem','Merritt C. Nieves','Te Deum','1969-04-09',2);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('quis lectus. Nullam suscipit,','Katelyn A. Perkins','Te Deum','1848-06-10',22);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('vitae, orci.','Abigail O. Cooper','Te Deum','1844-09-08',2);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('ridiculus mus. Proin vel','Kiayada T. Rodriquez','Te Deum','1844-11-27',9);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('neque. Morbi','Xaviera M. Douglas','Te Deum','1956-07-18',26);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('id,','Erica Y. Beasley','Te Deum','1846-08-13',15);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('leo. Morbi','Kai V. Kirby','Te Deum','1831-08-23',12);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('lobortis','Galena E. Scott','Wydawnictwo Akademickie „Dialog”','1966-12-08',24);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('neque. Nullam','Echo Q. Todd','Wydawnictwo Akademickie „Dialog”','1973-07-20',20);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('semper','Ahmed D. Mills','Wydawnictwo Akademickie „Dialog”','1874-02-04',7);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('aliquet nec,','Armando A. Slater','Noir sur Blanc','1950-10-31',22);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('Aliquam','Keith B. Gonzales','Noir sur Blanc','1895-06-18',20);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('dolor sit amet,','Debra L. Mercer','Noir sur Blanc','1912-08-14',2);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('molestie','Cara S. Emerson','Noir sur Blanc','1973-03-15',20);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('enim. Etiam imperdiet dictum','Sylvia P. Patrick','Noir sur Blanc','1900-11-16',19);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('ut','Sigourney R. Boone','Noir sur Blanc','2011-11-29',10);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('Aliquam vulputate ullamcorper magna.','Inga D. Weber','Noir sur Blanc','1905-03-04',8);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('placerat, orci','Lee S. Jenkins','Noir sur Blanc','1821-05-10',26);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('metus. In lorem. Donec','Honorato C. Cleveland','Noir sur Blanc','2020-01-08',12);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('libero est,','Anthony I. Stone','Noir sur Blanc','1992-08-18',22);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('viverra. Donec tempus,','Noble U. Lewis','ZamKor','1955-06-24',3);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('sed dictum eleifend, nunc','Keaton D. Alston','ZamKor','1956-11-23',19);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('Morbi vehicula.','Alexandra A. Love','ZamKor','1840-06-28',4);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('dui augue eu tellus.','Rudyard Z. Sherman','ZamKor','2011-01-23',3);
INSERT INTO Ksiazki([Tytul],[Autor],[Wydawnictwo],[DataWydania],[LiczbaDostepnych]) VALUES('interdum','Orla F. Short','ZamKor','1957-11-16',23);

INSERT INTO Pracownicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto],[DataZatrudnienia],[KodPocztowy],[Ulica]) VALUES('Courtney','2000-02-26','Hays','elit@et.edu','+90 850-133-017','Cape Breton Island','2017-06-16','7196','Ap #174-5196 Sodales Rd.');
INSERT INTO Pracownicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto],[DataZatrudnienia],[KodPocztowy],[Ulica]) VALUES('Lane','1961-05-29','Stark','Nam.nulla@per.co.uk','+46 958-655-170','Provo','2016-01-21','47600','710-6424 Dictum Street');
INSERT INTO Pracownicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto],[DataZatrudnienia],[KodPocztowy],[Ulica]) VALUES('Gillian','1957-04-26','Weaver','imperdiet@aliquet.co.uk','+83 241-966-144','Follina','2015-11-22','78737','8040 Lorem Avenue');
INSERT INTO Pracownicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto],[DataZatrudnienia],[KodPocztowy],[Ulica]) VALUES('Cathleen','1976-06-25','Dixon','aliquet.molestie@montes.edu','+04 387-096-080','Marcedusa','2017-09-23','44140','P.O. Box 842, 1729 Lectus. Av.');
INSERT INTO Pracownicy([Imie],[DataUrodzenia],[Nazwisko],[EMail],[NumerTelefonu],[Miasto],[DataZatrudnienia],[KodPocztowy],[Ulica]) VALUES('Karly','1982-01-13','Michael','justo.faucibus.lectus@blanditviverraDonec.net','+52 934-734-538','Podolsk','2017-04-30','85689','6190 Fusce Ave');